services:
  matrix:
    environment:
      - DISPLAY=${HOSTNAME}:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/bryce/.Xauthority:/root/.Xauthority
    build: .
    ports:
     - "8000:8000"
     # - "6000:6000"
     